name: kitlang
version: 'alpha'
author: Ben Morris <ben@bendmorris.com>
license: LGPL
license-file: LICENSE.md
dependencies:
- base >=4.7
default-extensions:
- OverloadedStrings
ghc-options: -O2 -optc-O3 -funfolding-use-threshold=16 -funbox-strict-fields -fexcess-precision -optc-ffast-math +RTS -A1024M -RTS -fmax-pmcheck-iterations=10000000
extra-source-files:
- "**/*.h"

library:
  source-dirs:
  - bin
  - src
  build-tools:
  - alex
  - happy
  exposed-modules:
  - Kit
  - Kit.Ast
  - Kit.Compiler
  - Kit.Compiler.Generators
  - Kit.Compiler.Generators.C
  - Kit.Compiler.Ir
  - Kit.Compiler.Passes
  - Kit.Error
  - Kit.HashTable
  - Kit.Ir
  - Kit.Log
  - Kit.Parser
  - Kit.Str
  dependencies:
  - ansi-terminal
  - array
  - async
  - base16-bytestring
  - bytestring
  - cryptohash-md5
  - directory
  - filepath
  - hashable
  - hashtables
  - language-c
  - mutable-containers
  - pretty
  - process
  - regex-posix
  - text
  - time
  - transformers
  - vector

executables:
  kitc:
    ghc-options: -rtsopts
    main: Main.hs
    source-dirs: bin/kitc
    dependencies:
    - ansi-terminal
    - kitlang
    - optparse-applicative ==0.14.2.0
    - process
    - time

tests:
  unit-tests:
    main: Test.hs
    source-dirs: tests
    ghc-options: -threaded
    build-tools:
    - alex
    - happy
    dependencies:
    - bytestring
    - directory
    - filepath
    - hspec
    - kitlang
    - language-c
    - mutable-containers
    - pretty
    - process
    - QuickCheck
    - temporary-rc
