<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>kit</string>
    </array>
    <key>name</key>
    <string>Kit</string>
    <key>scopeName</key>
    <string>source.kit</string>
    <key>uuid</key>
    <string>4fc8848b-af63-4ac5-850f-8e6b00a45004</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.function.kit</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.type.function.function.kit</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>10</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>12</key>
          <dict>
            <key>name</key>
            <string>support.type.function.return.kit</string>
          </dict>
          <key>13</key>
          <dict>
            <key>name</key>
            <string>support.type.function.return.kit</string>
          </dict>
          <key>14</key>
          <dict>
            <key>name</key>
            <string>support.type.function.return.kit</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.comma.kit</string>
          </dict>
          <key>11</key>
          <dict>
            <key>name</key>
            <string>keyword.control.arrow.kit</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b((function *)\((((([a-z_][a-zA-Z0-9_]*\.)+)?[A-Z][a-zA-Z0-9_\[\]]*)(, ))*((([a-z_][a-zA-Z0-9_]*\.)+)?[A-Z][a-zA-Z0-9_\[\]]*)\) *(->) *((([a-z_][a-zA-Z0-9_]*\.)+)?[A-Z][a-zA-Z0-9_\[\]]*))</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.kit</string>
        <key>match</key>
        <string>\b(import|include|function|implement|specialize|using|macro|rule|rules|typedef|trait)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>storage.modifier.kit</string>
        <key>match</key>
        <string>\b(private|public|static|inline)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.other.kit</string>
        <key>match</key>
        <string>\b(return|throw|for|as|in|if|then|else|do|while|match|default|unsafe|implicit|sizeof|continue|break)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>storage.type.kit</string>
        <key>match</key>
        <string>\b(struct|enum|union|abstract|var|const)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment.line.debug.kit</string>
        <key>match</key>
        <string>(?:[\t ]*)(?'line'\/\/ printf.*)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash.kit</string>
        <key>match</key>
        <string>(//).*$
?</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment.block.kit</string>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
      </dict>
      <dict>
        <key>name</key>
        <string>punctuation.separator.comma.kit</string>
        <key>match</key>
        <string>,</string>
      </dict>
      <dict>
        <key>name</key>
        <string>punctuation.separator.colon.kit</string>
        <key>match</key>
        <string>:</string>
      </dict>
      <dict>
        <key>name</key>
        <string>punctuation.separator.semicolon.kit</string>
        <key>match</key>
        <string>;</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.arrow.kit</string>
        <key>match</key>
        <string>=></string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.kit</string>
        <key>match</key>
        <string>(?<![\*\/\+\-\^\=\<\>\!\&\%\~\@\?\:\.])(<<=|>>=|<<|>>)(?![\*\/\+\-\^\=\<\>\!\&\%\~\@\?\:\.])</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.logical.kit</string>
        <key>match</key>
        <string>(?<![\*\/\+\-\^\=\<\>\!\&\%\~\@\?\:\.])(==|<=|>=|!=|>|<|\|\||&&|!)(?![\*\/\+\-\^\=\<\>\!\&\%\~\@\?\:\.])</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.kit</string>
        <key>match</key>
        <string>(?<![\*\/\+\-\^\=\<\>\!\&\%\~\@\?\:\.])((=|-|\+|--|\+\+|\*|%|&|\^|\||\~|\/|-=|\+=|\*=|\/=|%=)|((?<=[^\.])\.\.\.(?=[^\.]))|((?<=[^\.])\.(?=[^\.])))(?![\*\/\+\-\^\=\<\>\!\&\%\~\@\?\:\.])</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.custom.kit</string>
        <key>match</key>
        <string>[\*\/\+\-\^\=\<\>\!\&\%\~\@\?\:\.]+</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.language.kit</string>
        <key>match</key>
        <string>\b(this|Self)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>support.type.kit</string>
        <key>match</key>
        <string>\b((([a-z_][a-zA-Z0-9_]*\.)+)?[A-Z][a-zA-Z0-9_]*)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>punctuation.bracket.kit</string>
        <key>match</key>
        <string>\[|\]</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.decimal.kit</string>
        <key>match</key>
        <string>\b-?[0-9]+(\.[0-9]+)?(_([ui](8|16|32|64)|f(32|64)))?\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.octal.kit</string>
        <key>match</key>
        <string>\b-?0o[0-7]+(_([ui](8|16|32|64)|f(32|64)))?\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.hex.kit</string>
        <key>match</key>
        <string>\b-?0x[0-9a-f]+(_([ui](8|16|32|64)|f(32|64)))?\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.bin.kit</string>
        <key>match</key>
        <string>\b-?0b[01]+(_([ui](8|16|32|64)|f(32|64)))?\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.block.kit</string>
        <key>begin</key>
        <string>"""</string>
        <key>end</key>
        <string>"""</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.double.kit</string>
        <key>match</key>
        <string>"(?:\\"|[^"])*"</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.character.kit</string>
        <key>match</key>
        <string>c((\'.\')|(\'\\[abefnrtv\\\'\"?]\')|(\'\\[01234567]{1,3}\')|(\'\\x[0123456789aAbBcCdDeEfF]{2}\'))</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.single.kit</string>
        <key>match</key>
        <string>'(?:\\'|[^'])*'</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.language.kit</string>
        <key>match</key>
        <string>\b(true|false|null)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.expression.kit</string>
        <key>match</key>
        <string>(```( )*:(?=( )*\b[A-Z][a-zA-Z0-9_]*\b( )*;))|(```)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>markup.heading.metadata.kit</string>
        <key>begin</key>
        <string>\#\[</string>
        <key>end</key>
        <string>\]</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.function.main.kit</string>
        <key>match</key>
        <string>((?<=function )\bmain(?=\()\b)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.function.print.kit</string>
        <key>match</key>
        <string>(\bprintf(?=\()\b)|((?<!function )\bprint[a-zA-Z0-9_]*(?=\()\b)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.function.constructor.kit</string>
        <key>match</key>
        <string>(?<=\.)\bnew[a-zA-Z0-9_]*(?=\()\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.function.allocation.kit</string>
        <key>match</key>
        <string>(?<!function )((\bmalloc(?=\())|(\balloc(?=\())|(\brealloc(?=\())|(\bfree(?=\())|(\bcalloc(?=\()))</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.function.kit</string>
        <key>match</key>
        <string>(((?<=function )\b[a-z_][A-Za-z0-9_]*(?=\[[A-Z][A-Za-z0-9_]*\]\()))|(\b[a-z_][A-Za-z0-9_]*(?=\()\b)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.parameter.kit</string>
        <key>match</key>
        <string>\b[a-z_][A-Za-z0-9_]*\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>meta.preprocessor.rewrite.identifier.kit</string>
        <key>match</key>
        <string>\$[A-Za-z0-9_]+\b</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.dollarsign.kit</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.variable.kit</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.colon.kit</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.type.kit</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.type.kit</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.type.kit</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.comma.kit</string>
          </dict>
          <key>10</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.type.kit</string>
          </dict>
          <key>11</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.type.kit</string>
          </dict>
          <key>12</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.type.kit</string>
          </dict>
          <key>14</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.type.kit</string>
          </dict>
          <key>15</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.type.kit</string>
          </dict>
          <key>16</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.type.kit</string>
          </dict>
          <key>17</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.dollarsign.kit</string>
          </dict>
          <key>18</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.dollarsign.kit</string>
          </dict>
          <key>19</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.variable.kit</string>
          </dict>
          <key>20</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.colon.kit</string>
          </dict>
          <key>21</key>
          <dict>
            <key>name</key>
            <string>support.type.function.kit</string>
          </dict>
          <key>23</key>
          <dict>
            <key>name</key>
            <string>support.type.function.function.kit</string>
          </dict>
          <key>25</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>26</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>27</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>28</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.comma.kit</string>
          </dict>
          <key>29</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>30</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>31</key>
          <dict>
            <key>name</key>
            <string>support.type.function.input.kit</string>
          </dict>
          <key>32</key>
          <dict>
            <key>name</key>
            <string>keyword.control.arrow.kit</string>
          </dict>
          <key>33</key>
          <dict>
            <key>name</key>
            <string>support.type.function.return.kit</string>
          </dict>
          <key>34</key>
          <dict>
            <key>name</key>
            <string>support.type.function.return.kit</string>
          </dict>
          <key>35</key>
          <dict>
            <key>name</key>
            <string>support.type.function.return.kit</string>
          </dict>
          <key>36</key>
          <dict>
            <key>name</key>
            <string>meta.preprocessor.rewrite.dollarsign.kit</string>
          </dict>
        </dict>
        <key>match</key>
        <string>(\$\{)([a-z_][A-Za-z0-9_]*)(:)( *)(\((((([a-z_][a-zA-Z0-9_]*\.)+)?[A-Z][a-zA-Z0-9_\[\]]*)(, ))*((([a-z_][a-zA-Z0-9_]*\.)+)?[A-Z][a-zA-Z0-9_\[\]]*)\)|((([a-z_][a-zA-Z0-9_]*\.)+)?[A-Z][a-zA-Z0-9_\[\]]*))(\})|(\$\{)([a-z_][A-Za-z0-9_]*)(:)( *)((function *)\((((([a-z_][a-zA-Z0-9_]*\.)+)?[A-Z][a-zA-Z0-9_\[\]]*)(, ))*((([a-z_][a-zA-Z0-9_]*\.)+)?[A-Z][a-zA-Z0-9_\[\]]*)\) *(->) *((([a-z_][a-zA-Z0-9_]*\.)+)?[A-Z][a-zA-Z0-9_\[\]]*))(\})</string>
      </dict>
    </array>
  </dict>
</plist>
