<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>kit</string>
    </array>
    <key>name</key>
    <string>Kit</string>
    <key>scopeName</key>
    <string>source.kit</string>
    <key>uuid</key>
    <string>4fc8848b-af63-4ac5-850f-8e6b00a45004</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>match</key>
        <string>\b(import|include|function|implement|specialize|var|using)\b</string>
        <key>name</key>
        <string>keyword.control.kit</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(private|public|static|const|inline)\b</string>
        <key>name</key>
        <string>storage.modifier.kit</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(return|throw|for|as|in|if|then|else|do|while|match|default|unsafe|implicit|sizeof)\b</string>
        <key>name</key>
        <string>keyword.other.kit</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(struct|enum|union|abstract|rule|rules|typedef|trait)\b</string>
        <key>name</key>
        <string>storage.type.kit</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.arrow.kit</string>
        <key>match</key>
        <string>=\&gt;</string>
      </dict>
      <dict>
        <key>name</key>
        <string>support.type.kit</string>
        <key>match</key>
        <string>\b[A-Z][a-zA-Z0-9_]*\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.language.kit</string>
        <key>match</key>
        <string>\b(this|Self)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>invalid.illegal.macro.kit</string>
        <key>match</key>
        <string>\$[A-Za-z0-9_]+\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>invalid.illegal.macro.kit</string>
        <key>begin</key>
        <string>\$\{</string>
        <key>end</key>
        <string>\}</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.decimal.kit</string>
        <key>match</key>
        <string>-?[0-9]+(\.[0-9]+)?(_([ui](8|16|32|64)|f(32|64)))?</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.octal.kit</string>
        <key>match</key>
        <string>-?0o[0-7]+(_([ui](8|16|32|64)|f(32|64)))?</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.hex.kit</string>
        <key>match</key>
        <string>-?0x[0-9a-f]+(_([ui](8|16|32|64)|f(32|64)))?</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.bin.kit</string>
        <key>match</key>
        <string>-?0b[01]+(_([ui](8|16|32|64)|f(32|64)))?</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.block.kit</string>
        <key>begin</key>
        <string>"""</string>
        <key>end</key>
        <string>"""</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.double.kit</string>
        <key>match</key>
        <string>"(\.|[^"])*"</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.single.kit</string>
        <key>match</key>
        <string>'(\.|[^\'])*'</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash.kit</string>
        <key>match</key>
        <string>(//).*$
?</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment.block.kit</string>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.language.kit</string>
        <key>match</key>
        <string>\b(true|false|null)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>markup.heading.metadata.kit</string>
        <key>begin</key>
        <string>\#\[</string>
        <key>end</key>
        <string>\]</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.parameter.kit</string>
        <key>match</key>
        <string>\b[a-z_][A-Za-z0-9_]*\b</string>
      </dict>
    </array>
  </dict>
</plist>
